### ISSUE TITLE
C# Spec: sth about indentation symbol

### ISSUE THREAD

**Issue by KevinZonda** [DroidBeta/DroidBeta-Specification#7]
@Jisu-Woniu Anyway, **I don't think using tabular character  as indentation symbol is a good idea.** I think we should emphasize the need to use 4 spaces. C# is not golang, its indentation is not very constraining, in my word, it even looks more like a free spirit. But in any case, using tabs as C# indents is a stupid thing.

ref: <https://docs.microsoft.com/en-gb/dotnet/csharp/programming-guide/inside-a-program/coding-conventions#layout-conventions>
ref:  <https://download.microsoft.com/download/3/8/8/388e7205-bc10-4226-b2a8-75351c669b09/csharp%20language%20specification.doc>

**Comment by KevinZonda** [comment]
Especially, if you use GitHub webpage as your way to read codes, tabular character  makes terrible view experience. You know, tabular character always displays as 6 spaces.

**Comment by Jisu-Woniu** [comment]
I prefer to use Tabs because it adds convenience when we edit codes: we can add or delete an indent as a whole, without counting mistakes even if in a hurry.

**Comment by Jisu-Woniu** [comment]
Or we can use tabs "locally", and change it to spaces when releasing online.

**Comment by Jisu-Woniu** [comment]
Moreover, "sth" is used only in the dictionary.

**Comment by KevinZonda** [comment]
How stupid you are! 'Sth' is a very common abbreviation among the whole world. It is not only used in the dictionary but also in informal written. There are varieties of example sentences in *New English-Chinese Dictionary*. Also, you can find more on the Internet. Anyway, don't be mad as a mad dog bites, it can just demonstrate your silly. Remember that, your memory is not always right. There's no mind palace in your brain. :-)

**Comment by KevinZonda** [comment]
And, we should focus on the ISSUE but NOT morphology. If you always want to correct insignificant mistakes, plz go reddit, QOA or such forums. Or, PR typo-fix to any repositories you like.

**Comment by Jisu-Woniu** [comment]
It is a specification, we should always ensure the words we use are strict, even a small typo or misuse should be corrected.










jisu
xxq20011113@qq.com


---Original---

**Comment by Jisu-Woniu** [comment]
It is also very rude to make comments about others' intelligence. If you insist doing this, maybe you are not qualified for open-source communication.

**Comment by KevinZonda** [comment]
> It is a specification, we should always ensure the words we use are strict, even a small typo or misuse should be corrected.

**IT'S AN ISSUE!** If you don't know what occasion you're responding to, keep quiet.

**Comment by KevinZonda** [comment]
> It is also very rude to make comments about others' intelligence. If you insist doing this, maybe you are not qualified for open-source communication.

You are not qualified to talk to me, ***GENIUS***.
